# Generated by Django 5.1.2 on 2024-10-15 06:51

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rather',
            name='happy',
            field=banjo.models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rather',
            name='timechosen',
            field=banjo.models.IntegerField(default=0),
        ),
    ]
