# Generated by Django 5.1.2 on 2024-10-18 00:44

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_adjective_rather_noun2'),
    ]

    operations = [
        migrations.AddField(
            model_name='rather',
            name='wordclass',
            field=banjo.models.StringField(default=''),
        ),
    ]
