# Generated by Django 5.1.2 on 2024-10-18 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rather_wordclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rather',
            name='wordclass',
        ),
    ]
