# Generated by Django 5.1.2 on 2024-10-23 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_rather_wordclass'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rather',
            new_name='WouldYouRather',
        ),
        migrations.RenameField(
            model_name='wouldyourather',
            old_name='timechosen',
            new_name='timeschosen',
        ),
    ]
